"""MerchantOS AI Core Package."""

from merchantos_core.config import Settings
from merchantos_core.contracts import (
    CheckoutLineItem,
    CheckoutSnapshot,
    CurrencyINR,
    RazorpayOrder,
    RazorpayOrderNotes,
    RazorpayOrderRequest,
    RazorpayOrderStatus,
    RazorpayPaymentCapturedEvent,
    RazorpayPaymentEntity,
    RazorpayPaymentFailedEvent,
    RazorpayPaymentStatus,
    RazorpayWebhookEventName,
    RazorpayWebhookPaymentPayload,
    UnknownWebhookEvent,
    Product,
    MerchantPolicy,
    BuyerIntent,
    SimulatedScenario,
    AgentInput,
    ExtractedSignals,
    ProposedOffer,
    NegotiationEvent,
    BuyerResponse,
    NegotiationSessionState,
    LLMOutput,
    InventoryRecord,
    InventoryState,
    CumulativeLedger,
    PolicyCheck,
    CommerceDecision,
)
from merchantos_core.agents.growth_agent import MerchantGrowthAgent
from merchantos_core.agents.rules_baseline import RulesBaselineAgent
from merchantos_core.commerceproof.engine import CommerceProof
from merchantos_core.llm.provider import AbstractLLMProvider, MockLLMProvider
from merchantos_core.llm.prompts import build_merchant_prompt
from merchantos_core.negotiation.buyer_simulator import BuyerSimulator
from merchantos_core.negotiation.engine import NegotiationEngine
from merchantos_core.hashing import canonical_checkout_hash, sha256_hex

__all__ = [
    "Settings",
    "CurrencyINR",
    "RazorpayOrderStatus",
    "RazorpayPaymentStatus",
    "RazorpayWebhookEventName",
    "CheckoutLineItem",
    "CheckoutSnapshot",
    "RazorpayOrderNotes",
    "RazorpayOrderRequest",
    "RazorpayOrder",
    "RazorpayPaymentEntity",
    "RazorpayWebhookPaymentPayload",
    "RazorpayPaymentCapturedEvent",
    "RazorpayPaymentFailedEvent",
    "UnknownWebhookEvent",
    "Product",
    "MerchantPolicy",
    "BuyerIntent",
    "SimulatedScenario",
    "AgentInput",
    "ExtractedSignals",
    "ProposedOffer",
    "NegotiationEvent",
    "BuyerResponse",
    "NegotiationSessionState",
    "LLMOutput",
    "InventoryRecord",
    "InventoryState",
    "CumulativeLedger",
    "PolicyCheck",
    "CommerceDecision",
    "CommerceProof",
    "MerchantGrowthAgent",
    "RulesBaselineAgent",
    "AbstractLLMProvider",
    "MockLLMProvider",
    "build_merchant_prompt",
    "BuyerSimulator",
    "NegotiationEngine",
    "sha256_hex",
    "canonical_checkout_hash",
]
